C47_DismountVehicle/C0C47_JSI Joints_values_msg
C47_DismountVehicle/C0C47_TRN Terrain_Type_msg
C47_DismountVehicle/C0C47_SLP Slope_msg
---
C47_DismountVehicle/C47C0_Status Dismount_Vehicle_Status_msg
C47_DismountVehicle/C47C0_Err Dismount_Vehicle_Error_msg
