(cl:defpackage C41_QuasiStaticWalking-msg
  (:use )
  (:export
   "<QUASISTATICWALKINGACTIONRESULT>"
   "QUASISTATICWALKINGACTIONRESULT"
   "<QUASISTATICWALKINGRESULT>"
   "QUASISTATICWALKINGRESULT"
   "<QUASISTATICWALKINGACTIONGOAL>"
   "QUASISTATICWALKINGACTIONGOAL"
   "<QUASISTATICWALKINGFEEDBACK>"
   "QUASISTATICWALKINGFEEDBACK"
   "<QUASISTATICWALKINGACTIONFEEDBACK>"
   "QUASISTATICWALKINGACTIONFEEDBACK"
   "<QUASISTATICWALKINGACTION>"
   "QUASISTATICWALKINGACTION"
   "<QUASISTATICWALKINGGOAL>"
   "QUASISTATICWALKINGGOAL"
  ))

