; Auto-generated. Do not edit!


(cl:in-package C41_QuasiStaticWalking-msg)


;//! \htmlinclude QuasiStaticWalkingFeedback.msg.html

(cl:defclass <QuasiStaticWalkingFeedback> (roslisp-msg-protocol:ros-message)
  ((estimatedTime
    :reader estimatedTime
    :initarg :estimatedTime
    :type cl:float
    :initform 0.0))
)

(cl:defclass QuasiStaticWalkingFeedback (<QuasiStaticWalkingFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <QuasiStaticWalkingFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'QuasiStaticWalkingFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name C41_QuasiStaticWalking-msg:<QuasiStaticWalkingFeedback> is deprecated: use C41_QuasiStaticWalking-msg:QuasiStaticWalkingFeedback instead.")))

(cl:ensure-generic-function 'estimatedTime-val :lambda-list '(m))
(cl:defmethod estimatedTime-val ((m <QuasiStaticWalkingFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader C41_QuasiStaticWalking-msg:estimatedTime-val is deprecated.  Use C41_QuasiStaticWalking-msg:estimatedTime instead.")
  (estimatedTime m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <QuasiStaticWalkingFeedback>) ostream)
  "Serializes a message object of type '<QuasiStaticWalkingFeedback>"
  (cl:let ((bits (roslisp-utils:encode-single-float-bits (cl:slot-value msg 'estimatedTime))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <QuasiStaticWalkingFeedback>) istream)
  "Deserializes a message object of type '<QuasiStaticWalkingFeedback>"
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'estimatedTime) (roslisp-utils:decode-single-float-bits bits)))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<QuasiStaticWalkingFeedback>)))
  "Returns string type for a message object of type '<QuasiStaticWalkingFeedback>"
  "C41_QuasiStaticWalking/QuasiStaticWalkingFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'QuasiStaticWalkingFeedback)))
  "Returns string type for a message object of type 'QuasiStaticWalkingFeedback"
  "C41_QuasiStaticWalking/QuasiStaticWalkingFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<QuasiStaticWalkingFeedback>)))
  "Returns md5sum for a message object of type '<QuasiStaticWalkingFeedback>"
  "cf72ba555990520724340d6b9817aeee")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'QuasiStaticWalkingFeedback)))
  "Returns md5sum for a message object of type 'QuasiStaticWalkingFeedback"
  "cf72ba555990520724340d6b9817aeee")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<QuasiStaticWalkingFeedback>)))
  "Returns full string definition for message of type '<QuasiStaticWalkingFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%float32 estimatedTime~%~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'QuasiStaticWalkingFeedback)))
  "Returns full string definition for message of type 'QuasiStaticWalkingFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%float32 estimatedTime~%~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <QuasiStaticWalkingFeedback>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <QuasiStaticWalkingFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'QuasiStaticWalkingFeedback
    (cl:cons ':estimatedTime (estimatedTime msg))
))
