/* Auto-generated by genmsg_cpp for file /home/ariy/robil/RobilTask/msg/RobilTaskActionGoal.msg */
#ifndef ROBILTASK_MESSAGE_ROBILTASKACTIONGOAL_H
#define ROBILTASK_MESSAGE_ROBILTASKACTIONGOAL_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"
#include "actionlib_msgs/GoalID.h"
#include "RobilTask/RobilTaskGoal.h"

namespace RobilTask
{
template <class ContainerAllocator>
struct RobilTaskActionGoal_ {
  typedef RobilTaskActionGoal_<ContainerAllocator> Type;

  RobilTaskActionGoal_()
  : header()
  , goal_id()
  , goal()
  {
  }

  RobilTaskActionGoal_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , goal_id(_alloc)
  , goal(_alloc)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef  ::actionlib_msgs::GoalID_<ContainerAllocator>  _goal_id_type;
   ::actionlib_msgs::GoalID_<ContainerAllocator>  goal_id;

  typedef  ::RobilTask::RobilTaskGoal_<ContainerAllocator>  _goal_type;
   ::RobilTask::RobilTaskGoal_<ContainerAllocator>  goal;


  typedef boost::shared_ptr< ::RobilTask::RobilTaskActionGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::RobilTask::RobilTaskActionGoal_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct RobilTaskActionGoal
typedef  ::RobilTask::RobilTaskActionGoal_<std::allocator<void> > RobilTaskActionGoal;

typedef boost::shared_ptr< ::RobilTask::RobilTaskActionGoal> RobilTaskActionGoalPtr;
typedef boost::shared_ptr< ::RobilTask::RobilTaskActionGoal const> RobilTaskActionGoalConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::RobilTask::RobilTaskActionGoal_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::RobilTask::RobilTaskActionGoal_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace RobilTask

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::RobilTask::RobilTaskActionGoal_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::RobilTask::RobilTaskActionGoal_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::RobilTask::RobilTaskActionGoal_<ContainerAllocator> > {
  static const char* value() 
  {
    return "f1576ac633d4e0d114a876e23e8f4365";
  }

  static const char* value(const  ::RobilTask::RobilTaskActionGoal_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xf1576ac633d4e0d1ULL;
  static const uint64_t static_value2 = 0x14a876e23e8f4365ULL;
};

template<class ContainerAllocator>
struct DataType< ::RobilTask::RobilTaskActionGoal_<ContainerAllocator> > {
  static const char* value() 
  {
    return "RobilTask/RobilTaskActionGoal";
  }

  static const char* value(const  ::RobilTask::RobilTaskActionGoal_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::RobilTask::RobilTaskActionGoal_<ContainerAllocator> > {
  static const char* value() 
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
\n\
Header header\n\
actionlib_msgs/GoalID goal_id\n\
RobilTaskGoal goal\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: actionlib_msgs/GoalID\n\
# The stamp should store the time at which this goal was requested.\n\
# It is used by an action server when it tries to preempt all\n\
# goals that were requested before a certain time\n\
time stamp\n\
\n\
# The id provides a way to associate feedback and\n\
# result message with specific goal requests. The id\n\
# specified must be unique.\n\
string id\n\
\n\
\n\
================================================================================\n\
MSG: RobilTask/RobilTaskGoal\n\
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
# Define the goal\n\
string name\n\
string uid\n\
string parameters\n\
\n\
";
  }

  static const char* value(const  ::RobilTask::RobilTaskActionGoal_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::RobilTask::RobilTaskActionGoal_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::RobilTask::RobilTaskActionGoal_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::RobilTask::RobilTaskActionGoal_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.goal_id);
    stream.next(m.goal);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct RobilTaskActionGoal_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::RobilTask::RobilTaskActionGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::RobilTask::RobilTaskActionGoal_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "goal_id: ";
s << std::endl;
    Printer< ::actionlib_msgs::GoalID_<ContainerAllocator> >::stream(s, indent + "  ", v.goal_id);
    s << indent << "goal: ";
s << std::endl;
    Printer< ::RobilTask::RobilTaskGoal_<ContainerAllocator> >::stream(s, indent + "  ", v.goal);
  }
};


} // namespace message_operations
} // namespace ros

#endif // ROBILTASK_MESSAGE_ROBILTASKACTIONGOAL_H

