(cl:in-package C21_VisionAndLidar-srv)
(cl:export '(AZIMUTH_MSG-VAL
          AZIMUTH_MSG
          CAMERA_SAMPLE_RATE_MSG-VAL
          CAMERA_SAMPLE_RATE_MSG
          LASER_SAMPLE_RATE_MSG-VAL
          LASER_SAMPLE_RATE_MSG
          OUTPUT_IMAGE_SIZE_MSG-VAL
          OUTPUT_IMAGE_SIZE_MSG
          REQUIRED_RESOLUTION_MSG-VAL
          REQUIRED_RESOLUTION_MSG
          SCENE_FULL_RESOLUTION_MSG-VAL
          SCENE_FULL_RESOLUTION_MSG
          SCENE_REDUCED_RESOLUTION_MSG-VAL
          SCENE_REDUCED_RESOLUTION_MSG
))