/* Auto-generated by genmsg_cpp for file /home/ariy/robil/C66_Grasp/msg/C66_GraspResult.msg */
#ifndef C66_GRASP_MESSAGE_C66_GRASPRESULT_H
#define C66_GRASP_MESSAGE_C66_GRASPRESULT_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace C66_Grasp
{
template <class ContainerAllocator>
struct C66_GraspResult_ {
  typedef C66_GraspResult_<ContainerAllocator> Type;

  C66_GraspResult_()
  : success(false)
  {
  }

  C66_GraspResult_(const ContainerAllocator& _alloc)
  : success(false)
  {
  }

  typedef uint8_t _success_type;
  uint8_t success;


  typedef boost::shared_ptr< ::C66_Grasp::C66_GraspResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::C66_Grasp::C66_GraspResult_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct C66_GraspResult
typedef  ::C66_Grasp::C66_GraspResult_<std::allocator<void> > C66_GraspResult;

typedef boost::shared_ptr< ::C66_Grasp::C66_GraspResult> C66_GraspResultPtr;
typedef boost::shared_ptr< ::C66_Grasp::C66_GraspResult const> C66_GraspResultConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::C66_Grasp::C66_GraspResult_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::C66_Grasp::C66_GraspResult_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace C66_Grasp

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::C66_Grasp::C66_GraspResult_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::C66_Grasp::C66_GraspResult_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::C66_Grasp::C66_GraspResult_<ContainerAllocator> > {
  static const char* value() 
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const  ::C66_Grasp::C66_GraspResult_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x358e233cde0c8a8bULL;
  static const uint64_t static_value2 = 0xcfea4ce193f8fc15ULL;
};

template<class ContainerAllocator>
struct DataType< ::C66_Grasp::C66_GraspResult_<ContainerAllocator> > {
  static const char* value() 
  {
    return "C66_Grasp/C66_GraspResult";
  }

  static const char* value(const  ::C66_Grasp::C66_GraspResult_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::C66_Grasp::C66_GraspResult_<ContainerAllocator> > {
  static const char* value() 
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
#result definition\n\
bool success\n\
\n\
";
  }

  static const char* value(const  ::C66_Grasp::C66_GraspResult_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::C66_Grasp::C66_GraspResult_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::C66_Grasp::C66_GraspResult_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.success);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct C66_GraspResult_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::C66_Grasp::C66_GraspResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::C66_Grasp::C66_GraspResult_<ContainerAllocator> & v) 
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};


} // namespace message_operations
} // namespace ros

#endif // C66_GRASP_MESSAGE_C66_GRASPRESULT_H

