# This contains the position of 3 points that indicate the position
# of the Center of Mass in three different frames of coordinates:
# The first (num. 0) gives the CoM position in the root frame ("pelvis").
# The second (num. 1) gives the CoM position in the right foot frame ("r_foot"). 
# The third (num. 2) gives the CoM position in the left foot frame ("l_foot").

# geometry_msgs/Point root
# geometry_msgs/Point Rfoot
# geometry_msgs/Point Lfoot

Header header

float64[3] x 
float64[3] y
float64[3] z
