geometry_msgs/Vector3 PositionDestination_left
geometry_msgs/Vector3 AngleDestination_left
geometry_msgs/Vector3 PositionDestination_right
geometry_msgs/Vector3 AngleDestination_right
---
bool success
