/* Auto-generated by genmsg_cpp for file /home/ariy/robil/C11_Agent/msg/C34C11_STT.msg */
#ifndef C11_AGENT_MESSAGE_C34C11_STT_H
#define C11_AGENT_MESSAGE_C34C11_STT_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace C11_Agent
{
template <class ContainerAllocator>
struct C34C11_STT_ {
  typedef C34C11_STT_<ContainerAllocator> Type;

  C34C11_STT_()
  : stt(0)
  {
  }

  C34C11_STT_(const ContainerAllocator& _alloc)
  : stt(0)
  {
  }

  typedef int8_t _stt_type;
  int8_t stt;


  typedef boost::shared_ptr< ::C11_Agent::C34C11_STT_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::C11_Agent::C34C11_STT_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct C34C11_STT
typedef  ::C11_Agent::C34C11_STT_<std::allocator<void> > C34C11_STT;

typedef boost::shared_ptr< ::C11_Agent::C34C11_STT> C34C11_STTPtr;
typedef boost::shared_ptr< ::C11_Agent::C34C11_STT const> C34C11_STTConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::C11_Agent::C34C11_STT_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::C11_Agent::C34C11_STT_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace C11_Agent

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::C11_Agent::C34C11_STT_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::C11_Agent::C34C11_STT_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::C11_Agent::C34C11_STT_<ContainerAllocator> > {
  static const char* value() 
  {
    return "650018e0b258e00520bce2e8b307e19f";
  }

  static const char* value(const  ::C11_Agent::C34C11_STT_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x650018e0b258e005ULL;
  static const uint64_t static_value2 = 0x20bce2e8b307e19fULL;
};

template<class ContainerAllocator>
struct DataType< ::C11_Agent::C34C11_STT_<ContainerAllocator> > {
  static const char* value() 
  {
    return "C11_Agent/C34C11_STT";
  }

  static const char* value(const  ::C11_Agent::C34C11_STT_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::C11_Agent::C34C11_STT_<ContainerAllocator> > {
  static const char* value() 
  {
    return "int8 stt\n\
\n\
\n\
";
  }

  static const char* value(const  ::C11_Agent::C34C11_STT_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::C11_Agent::C34C11_STT_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::C11_Agent::C34C11_STT_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.stt);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct C34C11_STT_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::C11_Agent::C34C11_STT_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::C11_Agent::C34C11_STT_<ContainerAllocator> & v) 
  {
    s << indent << "stt: ";
    Printer<int8_t>::stream(s, indent + "  ", v.stt);
  }
};


} // namespace message_operations
} // namespace ros

#endif // C11_AGENT_MESSAGE_C34C11_STT_H

