"""autogenerated by genpy from C42_Leg_IK/LegAngle.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class LegAngle(genpy.Message):
  _md5sum = "1d76d2a214e8a6ad77f94d476f75a48c"
  _type = "C42_Leg_IK/LegAngle"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """float64 mhx
float64 lhy
float64 uhz
float64 kny
float64 lax
float64 uay
float64 mby
float64 ubx

"""
  __slots__ = ['mhx','lhy','uhz','kny','lax','uay','mby','ubx']
  _slot_types = ['float64','float64','float64','float64','float64','float64','float64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       mhx,lhy,uhz,kny,lax,uay,mby,ubx

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(LegAngle, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.mhx is None:
        self.mhx = 0.
      if self.lhy is None:
        self.lhy = 0.
      if self.uhz is None:
        self.uhz = 0.
      if self.kny is None:
        self.kny = 0.
      if self.lax is None:
        self.lax = 0.
      if self.uay is None:
        self.uay = 0.
      if self.mby is None:
        self.mby = 0.
      if self.ubx is None:
        self.ubx = 0.
    else:
      self.mhx = 0.
      self.lhy = 0.
      self.uhz = 0.
      self.kny = 0.
      self.lax = 0.
      self.uay = 0.
      self.mby = 0.
      self.ubx = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_8d.pack(_x.mhx, _x.lhy, _x.uhz, _x.kny, _x.lax, _x.uay, _x.mby, _x.ubx))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 64
      (_x.mhx, _x.lhy, _x.uhz, _x.kny, _x.lax, _x.uay, _x.mby, _x.ubx,) = _struct_8d.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_8d.pack(_x.mhx, _x.lhy, _x.uhz, _x.kny, _x.lax, _x.uay, _x.mby, _x.ubx))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 64
      (_x.mhx, _x.lhy, _x.uhz, _x.kny, _x.lax, _x.uay, _x.mby, _x.ubx,) = _struct_8d.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_8d = struct.Struct("<8d")
