; Auto-generated. Do not edit!


(cl:in-package C42_LocomotionAndStability-msg)


;//! \htmlinclude C34C42_PSU.msg.html

(cl:defclass <C34C42_PSU> (roslisp-msg-protocol:ros-message)
  ((PSU_DVEL
    :reader PSU_DVEL
    :initarg :PSU_DVEL
    :type (cl:vector cl:float)
   :initform (cl:make-array 0 :element-type 'cl:float :initial-element 0.0))
   (PSU_VP_POS
    :reader PSU_VP_POS
    :initarg :PSU_VP_POS
    :type (cl:vector cl:float)
   :initform (cl:make-array 0 :element-type 'cl:float :initial-element 0.0))
   (PSU_VP_OR
    :reader PSU_VP_OR
    :initarg :PSU_VP_OR
    :type (cl:vector cl:float)
   :initform (cl:make-array 0 :element-type 'cl:float :initial-element 0.0))
   (PSU_VP_TOL
    :reader PSU_VP_TOL
    :initarg :PSU_VP_TOL
    :type (cl:vector cl:float)
   :initform (cl:make-array 0 :element-type 'cl:float :initial-element 0.0)))
)

(cl:defclass C34C42_PSU (<C34C42_PSU>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <C34C42_PSU>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'C34C42_PSU)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name C42_LocomotionAndStability-msg:<C34C42_PSU> is deprecated: use C42_LocomotionAndStability-msg:C34C42_PSU instead.")))

(cl:ensure-generic-function 'PSU_DVEL-val :lambda-list '(m))
(cl:defmethod PSU_DVEL-val ((m <C34C42_PSU>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader C42_LocomotionAndStability-msg:PSU_DVEL-val is deprecated.  Use C42_LocomotionAndStability-msg:PSU_DVEL instead.")
  (PSU_DVEL m))

(cl:ensure-generic-function 'PSU_VP_POS-val :lambda-list '(m))
(cl:defmethod PSU_VP_POS-val ((m <C34C42_PSU>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader C42_LocomotionAndStability-msg:PSU_VP_POS-val is deprecated.  Use C42_LocomotionAndStability-msg:PSU_VP_POS instead.")
  (PSU_VP_POS m))

(cl:ensure-generic-function 'PSU_VP_OR-val :lambda-list '(m))
(cl:defmethod PSU_VP_OR-val ((m <C34C42_PSU>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader C42_LocomotionAndStability-msg:PSU_VP_OR-val is deprecated.  Use C42_LocomotionAndStability-msg:PSU_VP_OR instead.")
  (PSU_VP_OR m))

(cl:ensure-generic-function 'PSU_VP_TOL-val :lambda-list '(m))
(cl:defmethod PSU_VP_TOL-val ((m <C34C42_PSU>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader C42_LocomotionAndStability-msg:PSU_VP_TOL-val is deprecated.  Use C42_LocomotionAndStability-msg:PSU_VP_TOL instead.")
  (PSU_VP_TOL m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <C34C42_PSU>) ostream)
  "Serializes a message object of type '<C34C42_PSU>"
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'PSU_DVEL))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let ((bits (roslisp-utils:encode-single-float-bits ele)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)))
   (cl:slot-value msg 'PSU_DVEL))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'PSU_VP_POS))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let ((bits (roslisp-utils:encode-single-float-bits ele)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)))
   (cl:slot-value msg 'PSU_VP_POS))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'PSU_VP_OR))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let ((bits (roslisp-utils:encode-single-float-bits ele)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)))
   (cl:slot-value msg 'PSU_VP_OR))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'PSU_VP_TOL))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let ((bits (roslisp-utils:encode-single-float-bits ele)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)))
   (cl:slot-value msg 'PSU_VP_TOL))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <C34C42_PSU>) istream)
  "Deserializes a message object of type '<C34C42_PSU>"
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'PSU_DVEL) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'PSU_DVEL)))
    (cl:dotimes (i __ros_arr_len)
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:aref vals i) (roslisp-utils:decode-single-float-bits bits))))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'PSU_VP_POS) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'PSU_VP_POS)))
    (cl:dotimes (i __ros_arr_len)
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:aref vals i) (roslisp-utils:decode-single-float-bits bits))))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'PSU_VP_OR) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'PSU_VP_OR)))
    (cl:dotimes (i __ros_arr_len)
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:aref vals i) (roslisp-utils:decode-single-float-bits bits))))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'PSU_VP_TOL) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'PSU_VP_TOL)))
    (cl:dotimes (i __ros_arr_len)
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:aref vals i) (roslisp-utils:decode-single-float-bits bits))))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<C34C42_PSU>)))
  "Returns string type for a message object of type '<C34C42_PSU>"
  "C42_LocomotionAndStability/C34C42_PSU")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'C34C42_PSU)))
  "Returns string type for a message object of type 'C34C42_PSU"
  "C42_LocomotionAndStability/C34C42_PSU")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<C34C42_PSU>)))
  "Returns md5sum for a message object of type '<C34C42_PSU>"
  "f55fbce5db6d80be1a3e44223e3f3fa5")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'C34C42_PSU)))
  "Returns md5sum for a message object of type 'C34C42_PSU"
  "f55fbce5db6d80be1a3e44223e3f3fa5")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<C34C42_PSU>)))
  "Returns full string definition for message of type '<C34C42_PSU>"
  (cl:format cl:nil "float32[] PSU_DVEL~%float32[] PSU_VP_POS~%float32[] PSU_VP_OR~%float32[] PSU_VP_TOL~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'C34C42_PSU)))
  "Returns full string definition for message of type 'C34C42_PSU"
  (cl:format cl:nil "float32[] PSU_DVEL~%float32[] PSU_VP_POS~%float32[] PSU_VP_OR~%float32[] PSU_VP_TOL~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <C34C42_PSU>))
  (cl:+ 0
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'PSU_DVEL) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 4)))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'PSU_VP_POS) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 4)))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'PSU_VP_OR) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 4)))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'PSU_VP_TOL) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 4)))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <C34C42_PSU>))
  "Converts a ROS message object to a list"
  (cl:list 'C34C42_PSU
    (cl:cons ':PSU_DVEL (PSU_DVEL msg))
    (cl:cons ':PSU_VP_POS (PSU_VP_POS msg))
    (cl:cons ':PSU_VP_OR (PSU_VP_OR msg))
    (cl:cons ':PSU_VP_TOL (PSU_VP_TOL msg))
))
