(cl:defpackage C45_PostureControl-msg
  (:use )
  (:export
   "<POSTURECONTROLGOAL>"
   "POSTURECONTROLGOAL"
   "<POSTURECONTROLACTIONRESULT>"
   "POSTURECONTROLACTIONRESULT"
   "<POSTURECONTROLACTIONFEEDBACK>"
   "POSTURECONTROLACTIONFEEDBACK"
   "<POSTURECONTROLACTIONGOAL>"
   "POSTURECONTROLACTIONGOAL"
   "<POSTURECONTROLACTION>"
   "POSTURECONTROLACTION"
   "<POSTURECONTROLFEEDBACK>"
   "POSTURECONTROLFEEDBACK"
   "<POSTURECONTROLRESULT>"
   "POSTURECONTROLRESULT"
  ))

