(cl:defpackage C45_PostureControl-msg
  (:use )
  (:export
   "<POSTURECONTROLGOAL>"
   "POSTURECONTROLGOAL"
   "<POSTURECONTROLACTIONRESULT>"
   "POSTURECONTROLACTIONRESULT"
   "<C45C0_EVE>"
   "C45C0_EVE"
   "<C34C45_PM>"
   "C34C45_PM"
   "<C34C45_PSU>"
   "C34C45_PSU"
   "<POSTURECONTROLACTIONFEEDBACK>"
   "POSTURECONTROLACTIONFEEDBACK"
   "<POSTURECONTROLACTIONGOAL>"
   "POSTURECONTROLACTIONGOAL"
   "<POSTURECONTROLACTION>"
   "POSTURECONTROLACTION"
   "<POSTURECONTROLFEEDBACK>"
   "POSTURECONTROLFEEDBACK"
   "<POSTURECONTROLRESULT>"
   "POSTURECONTROLRESULT"
   "<C22C45_SSL>"
   "C22C45_SSL"
  ))

