(cl:in-package C44_ClimbLadder-srv)
(cl:export '(LADDER_DIMENSIONS_MSG-VAL
          LADDER_DIMENSIONS_MSG
          DISTANCE_BETWEEN_STEPS_MSG-VAL
          DISTANCE_BETWEEN_STEPS_MSG
          CLIMB_A_LADDER_SUCCESS_MSG-VAL
          CLIMB_A_LADDER_SUCCESS_MSG
))