/* Auto-generated by genmsg_cpp for file /home/ariy/robil/C41_BodyControl/msg/C41C0_AT.msg */
#ifndef C41_BODYCONTROL_MESSAGE_C41C0_AT_H
#define C41_BODYCONTROL_MESSAGE_C41C0_AT_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace C41_BodyControl
{
template <class ContainerAllocator>
struct C41C0_AT_ {
  typedef C41C0_AT_<ContainerAllocator> Type;

  C41C0_AT_()
  : Actual_torque()
  {
  }

  C41C0_AT_(const ContainerAllocator& _alloc)
  : Actual_torque(_alloc)
  {
  }

  typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _Actual_torque_type;
  std::vector<float, typename ContainerAllocator::template rebind<float>::other >  Actual_torque;


  typedef boost::shared_ptr< ::C41_BodyControl::C41C0_AT_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::C41_BodyControl::C41C0_AT_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct C41C0_AT
typedef  ::C41_BodyControl::C41C0_AT_<std::allocator<void> > C41C0_AT;

typedef boost::shared_ptr< ::C41_BodyControl::C41C0_AT> C41C0_ATPtr;
typedef boost::shared_ptr< ::C41_BodyControl::C41C0_AT const> C41C0_ATConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::C41_BodyControl::C41C0_AT_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::C41_BodyControl::C41C0_AT_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace C41_BodyControl

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::C41_BodyControl::C41C0_AT_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::C41_BodyControl::C41C0_AT_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::C41_BodyControl::C41C0_AT_<ContainerAllocator> > {
  static const char* value() 
  {
    return "a5c3064b8b8d3738379e0d1cc54f0366";
  }

  static const char* value(const  ::C41_BodyControl::C41C0_AT_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xa5c3064b8b8d3738ULL;
  static const uint64_t static_value2 = 0x379e0d1cc54f0366ULL;
};

template<class ContainerAllocator>
struct DataType< ::C41_BodyControl::C41C0_AT_<ContainerAllocator> > {
  static const char* value() 
  {
    return "C41_BodyControl/C41C0_AT";
  }

  static const char* value(const  ::C41_BodyControl::C41C0_AT_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::C41_BodyControl::C41C0_AT_<ContainerAllocator> > {
  static const char* value() 
  {
    return "float32[] Actual_torque \n\
\n\
";
  }

  static const char* value(const  ::C41_BodyControl::C41C0_AT_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::C41_BodyControl::C41C0_AT_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.Actual_torque);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct C41C0_AT_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::C41_BodyControl::C41C0_AT_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::C41_BodyControl::C41C0_AT_<ContainerAllocator> & v) 
  {
    s << indent << "Actual_torque[]" << std::endl;
    for (size_t i = 0; i < v.Actual_torque.size(); ++i)
    {
      s << indent << "  Actual_torque[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.Actual_torque[i]);
    }
  }
};


} // namespace message_operations
} // namespace ros

#endif // C41_BODYCONTROL_MESSAGE_C41C0_AT_H

