/* Auto-generated by genmsg_cpp for file /home/ariy/workspace/Executer/srv/pause.srv */
#ifndef EXECUTER_SERVICE_PAUSE_H
#define EXECUTER_SERVICE_PAUSE_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "ros/service_traits.h"




namespace Executer
{
template <class ContainerAllocator>
struct pauseRequest_ {
  typedef pauseRequest_<ContainerAllocator> Type;

  pauseRequest_()
  : tree_id()
  {
  }

  pauseRequest_(const ContainerAllocator& _alloc)
  : tree_id(_alloc)
  {
  }

  typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _tree_id_type;
  std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  tree_id;


  typedef boost::shared_ptr< ::Executer::pauseRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::Executer::pauseRequest_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct pauseRequest
typedef  ::Executer::pauseRequest_<std::allocator<void> > pauseRequest;

typedef boost::shared_ptr< ::Executer::pauseRequest> pauseRequestPtr;
typedef boost::shared_ptr< ::Executer::pauseRequest const> pauseRequestConstPtr;


template <class ContainerAllocator>
struct pauseResponse_ {
  typedef pauseResponse_<ContainerAllocator> Type;

  pauseResponse_()
  : output()
  {
  }

  pauseResponse_(const ContainerAllocator& _alloc)
  : output(_alloc)
  {
  }

  typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _output_type;
  std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  output;


  typedef boost::shared_ptr< ::Executer::pauseResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::Executer::pauseResponse_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct pauseResponse
typedef  ::Executer::pauseResponse_<std::allocator<void> > pauseResponse;

typedef boost::shared_ptr< ::Executer::pauseResponse> pauseResponsePtr;
typedef boost::shared_ptr< ::Executer::pauseResponse const> pauseResponseConstPtr;

struct pause
{

typedef pauseRequest Request;
typedef pauseResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;
}; // struct pause
} // namespace Executer

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::Executer::pauseRequest_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::Executer::pauseRequest_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::Executer::pauseRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "035d9dc2af2b0acc4c1fca0de404f272";
  }

  static const char* value(const  ::Executer::pauseRequest_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x035d9dc2af2b0accULL;
  static const uint64_t static_value2 = 0x4c1fca0de404f272ULL;
};

template<class ContainerAllocator>
struct DataType< ::Executer::pauseRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Executer/pauseRequest";
  }

  static const char* value(const  ::Executer::pauseRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::Executer::pauseRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "string tree_id\n\
\n\
";
  }

  static const char* value(const  ::Executer::pauseRequest_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros


namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::Executer::pauseResponse_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::Executer::pauseResponse_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::Executer::pauseResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "0825d95fdfa2c8f4bbb4e9c74bccd3fd";
  }

  static const char* value(const  ::Executer::pauseResponse_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x0825d95fdfa2c8f4ULL;
  static const uint64_t static_value2 = 0xbbb4e9c74bccd3fdULL;
};

template<class ContainerAllocator>
struct DataType< ::Executer::pauseResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Executer/pauseResponse";
  }

  static const char* value(const  ::Executer::pauseResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::Executer::pauseResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "string output\n\
\n\
\n\
";
  }

  static const char* value(const  ::Executer::pauseResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::Executer::pauseRequest_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.tree_id);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct pauseRequest_
} // namespace serialization
} // namespace ros


namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::Executer::pauseResponse_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.output);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct pauseResponse_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace service_traits
{
template<>
struct MD5Sum<Executer::pause> {
  static const char* value() 
  {
    return "2d787918d0efb6823e526f109f8fafe3";
  }

  static const char* value(const Executer::pause&) { return value(); } 
};

template<>
struct DataType<Executer::pause> {
  static const char* value() 
  {
    return "Executer/pause";
  }

  static const char* value(const Executer::pause&) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<Executer::pauseRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "2d787918d0efb6823e526f109f8fafe3";
  }

  static const char* value(const Executer::pauseRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<Executer::pauseRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Executer/pause";
  }

  static const char* value(const Executer::pauseRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<Executer::pauseResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "2d787918d0efb6823e526f109f8fafe3";
  }

  static const char* value(const Executer::pauseResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<Executer::pauseResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Executer/pause";
  }

  static const char* value(const Executer::pauseResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace service_traits
} // namespace ros

#endif // EXECUTER_SERVICE_PAUSE_H

