C46_MountVehicle/C0C46_JSI Joints_information_msg
C46_MountVehicle/C0C46_LSI Links_information_msg
C46_MountVehicle/C0C46_CI Car_information_msg
---
C46_MountVehicle/C46C0_Status Mount_Vehicle_Status_msg
C46_MountVehicle/C46C0_Err Mount_Vehicle_Error_msg
