(cl:in-package C41_BodyControl-srv)
(cl:export '(WORK_MODE_MSG-VAL
          WORK_MODE_MSG
          TORQUE_CONTROL_MSG-VAL
          TORQUE_CONTROL_MSG
          POSITION_VELOCITY_ACELERATION_CONTROL_MSG-VAL
          POSITION_VELOCITY_ACELERATION_CONTROL_MSG
          EXTERNAL_LOAD_MSG-VAL
          EXTERNAL_LOAD_MSG
          ACTUAL_TORQUE_ON_EACH_JOINT_MSG-VAL
          ACTUAL_TORQUE_ON_EACH_JOINT_MSG
          ACTUAL_POSITION_VELOCITY_ACCELERATION_OF_EACH_JOINT_MSG-VAL
          ACTUAL_POSITION_VELOCITY_ACCELERATION_OF_EACH_JOINT_MSG
))