(cl:in-package C51_CarOperation-srv)
(cl:export '(CAR_CLASS-VAL
          CAR_CLASS
          START_STOP_CAR-VAL
          START_STOP_CAR
          VELOCITY_PARAMETERS-VAL
          VELOCITY_PARAMETERS
          TRAVEL_PARAMETERS-VAL
          TRAVEL_PARAMETERS
          NORMAL_ABNORMAL_TRAVEL-VAL
          NORMAL_ABNORMAL_TRAVEL
          CAR_POSITION-VAL
          CAR_POSITION
))