/* Auto-generated by genmsg_cpp for file /home/ariy/robil/C23_ObjectRecognition/msg/C0C23_SEC.msg */
#ifndef C23_OBJECTRECOGNITION_MESSAGE_C0C23_SEC_H
#define C23_OBJECTRECOGNITION_MESSAGE_C0C23_SEC_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace C23_ObjectRecognition
{
template <class ContainerAllocator>
struct C0C23_SEC_ {
  typedef C0C23_SEC_<ContainerAllocator> Type;

  C0C23_SEC_()
  : searchMode(0)
  {
  }

  C0C23_SEC_(const ContainerAllocator& _alloc)
  : searchMode(0)
  {
  }

  typedef int32_t _searchMode_type;
  int32_t searchMode;


  typedef boost::shared_ptr< ::C23_ObjectRecognition::C0C23_SEC_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::C23_ObjectRecognition::C0C23_SEC_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct C0C23_SEC
typedef  ::C23_ObjectRecognition::C0C23_SEC_<std::allocator<void> > C0C23_SEC;

typedef boost::shared_ptr< ::C23_ObjectRecognition::C0C23_SEC> C0C23_SECPtr;
typedef boost::shared_ptr< ::C23_ObjectRecognition::C0C23_SEC const> C0C23_SECConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::C23_ObjectRecognition::C0C23_SEC_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::C23_ObjectRecognition::C0C23_SEC_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace C23_ObjectRecognition

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::C23_ObjectRecognition::C0C23_SEC_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::C23_ObjectRecognition::C0C23_SEC_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::C23_ObjectRecognition::C0C23_SEC_<ContainerAllocator> > {
  static const char* value() 
  {
    return "bae3fff7963613e512fc7eb6fb3103b8";
  }

  static const char* value(const  ::C23_ObjectRecognition::C0C23_SEC_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xbae3fff7963613e5ULL;
  static const uint64_t static_value2 = 0x12fc7eb6fb3103b8ULL;
};

template<class ContainerAllocator>
struct DataType< ::C23_ObjectRecognition::C0C23_SEC_<ContainerAllocator> > {
  static const char* value() 
  {
    return "C23_ObjectRecognition/C0C23_SEC";
  }

  static const char* value(const  ::C23_ObjectRecognition::C0C23_SEC_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::C23_ObjectRecognition::C0C23_SEC_<ContainerAllocator> > {
  static const char* value() 
  {
    return "int32 searchMode\n\
\n\
";
  }

  static const char* value(const  ::C23_ObjectRecognition::C0C23_SEC_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::C23_ObjectRecognition::C0C23_SEC_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::C23_ObjectRecognition::C0C23_SEC_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.searchMode);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct C0C23_SEC_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::C23_ObjectRecognition::C0C23_SEC_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::C23_ObjectRecognition::C0C23_SEC_<ContainerAllocator> & v) 
  {
    s << indent << "searchMode: ";
    Printer<int32_t>::stream(s, indent + "  ", v.searchMode);
  }
};


} // namespace message_operations
} // namespace ros

#endif // C23_OBJECTRECOGNITION_MESSAGE_C0C23_SEC_H

