/* Auto-generated by genmsg_cpp for file /home/ariy/robil/C23_ObjectRecognition/msg/TBD.msg */
#ifndef C23_OBJECTRECOGNITION_MESSAGE_TBD_H
#define C23_OBJECTRECOGNITION_MESSAGE_TBD_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace C23_ObjectRecognition
{
template <class ContainerAllocator>
struct TBD_ {
  typedef TBD_<ContainerAllocator> Type;

  TBD_()
  : x(0)
  , y(0)
  , z(0)
  {
  }

  TBD_(const ContainerAllocator& _alloc)
  : x(0)
  , y(0)
  , z(0)
  {
  }

  typedef int32_t _x_type;
  int32_t x;

  typedef int32_t _y_type;
  int32_t y;

  typedef int32_t _z_type;
  int32_t z;


  typedef boost::shared_ptr< ::C23_ObjectRecognition::TBD_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::C23_ObjectRecognition::TBD_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct TBD
typedef  ::C23_ObjectRecognition::TBD_<std::allocator<void> > TBD;

typedef boost::shared_ptr< ::C23_ObjectRecognition::TBD> TBDPtr;
typedef boost::shared_ptr< ::C23_ObjectRecognition::TBD const> TBDConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::C23_ObjectRecognition::TBD_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::C23_ObjectRecognition::TBD_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace C23_ObjectRecognition

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::C23_ObjectRecognition::TBD_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::C23_ObjectRecognition::TBD_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::C23_ObjectRecognition::TBD_<ContainerAllocator> > {
  static const char* value() 
  {
    return "3cb41a2c4416de195dbb95b7777a06fb";
  }

  static const char* value(const  ::C23_ObjectRecognition::TBD_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x3cb41a2c4416de19ULL;
  static const uint64_t static_value2 = 0x5dbb95b7777a06fbULL;
};

template<class ContainerAllocator>
struct DataType< ::C23_ObjectRecognition::TBD_<ContainerAllocator> > {
  static const char* value() 
  {
    return "C23_ObjectRecognition/TBD";
  }

  static const char* value(const  ::C23_ObjectRecognition::TBD_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::C23_ObjectRecognition::TBD_<ContainerAllocator> > {
  static const char* value() 
  {
    return "int32 x\n\
int32 y\n\
int32 z\n\
\n\
";
  }

  static const char* value(const  ::C23_ObjectRecognition::TBD_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::C23_ObjectRecognition::TBD_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::C23_ObjectRecognition::TBD_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.x);
    stream.next(m.y);
    stream.next(m.z);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct TBD_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::C23_ObjectRecognition::TBD_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::C23_ObjectRecognition::TBD_<ContainerAllocator> & v) 
  {
    s << indent << "x: ";
    Printer<int32_t>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<int32_t>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<int32_t>::stream(s, indent + "  ", v.z);
  }
};


} // namespace message_operations
} // namespace ros

#endif // C23_OBJECTRECOGNITION_MESSAGE_TBD_H

