/**************************************************************************************
 * This is a template for the c11_Operator_control module for the robil project
 * The c11_Operator_control module goal is to provide the operator control
 * There is no actual input/output at this time, this goes according to the current milestone
 * set at the robil management meeting
 * 
 **************************************************************************************/

#include "ros/ros.h"
#include "C11_OperatorControl/C11.h"

/**
 * this class represent the C11_Node,
 * it subscribe to two camera/image topics and provide the path
 **/
class C11_Node{

public:

	/**
	 * constructor, initializes the ROS node, subscribe it to the given topics and instruct it to provide the service
	 */
	  C11_Node()
	  {
		service = nh_.advertiseService("C11", &C11_Node::proccess, this); //Specifying what to do when a service is requested
		ROS_INFO("service on\n");
	  }


	  /**
	   * The call back function executed when a service is requested
	   * it must return true in order to work properly
	   * @param req the request message, generated by the node requesting the service
	   * @param res the response message, generated by the service node when a service is requested
	   */
	  bool proccess(C11_OperatorControl::C11::Request  &req,
			C11_OperatorControl::C11::Response &res )
	  {
		  ROS_INFO("recived request, tying to fetch data\n");

		  return true;
	  }


private:
  ros::NodeHandle nh_;
  ros::ServiceServer service;
};

int main(int argc, char **argv)
{
  ros::init(argc, argv, "C11_OperatorControl");
  C11_Node my_node();
  while(ros::ok()){
	  ros::spin();
  }
  return 0;
}

