(cl:defpackage C66_Grasp-msg
  (:use )
  (:export
   "<C66_GRASPFEEDBACK>"
   "C66_GRASPFEEDBACK"
   "<C66_GRASPACTIONRESULT>"
   "C66_GRASPACTIONRESULT"
   "<C66_GRASPGOAL>"
   "C66_GRASPGOAL"
   "<C66_GRASPACTION>"
   "C66_GRASPACTION"
   "<C66_GRASPACTIONGOAL>"
   "C66_GRASPACTIONGOAL"
   "<C66_GRASPACTIONFEEDBACK>"
   "C66_GRASPACTIONFEEDBACK"
   "<C66_GRASPRESULT>"
   "C66_GRASPRESULT"
  ))

