; Auto-generated. Do not edit!


(cl:in-package C66_Grasp-msg)


;//! \htmlinclude C66_GraspActionGoal.msg.html

(cl:defclass <C66_GraspActionGoal> (roslisp-msg-protocol:ros-message)
  ((header
    :reader header
    :initarg :header
    :type std_msgs-msg:Header
    :initform (cl:make-instance 'std_msgs-msg:Header))
   (goal_id
    :reader goal_id
    :initarg :goal_id
    :type actionlib_msgs-msg:GoalID
    :initform (cl:make-instance 'actionlib_msgs-msg:GoalID))
   (goal
    :reader goal
    :initarg :goal
    :type C66_Grasp-msg:C66_GraspGoal
    :initform (cl:make-instance 'C66_Grasp-msg:C66_GraspGoal)))
)

(cl:defclass C66_GraspActionGoal (<C66_GraspActionGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <C66_GraspActionGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'C66_GraspActionGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name C66_Grasp-msg:<C66_GraspActionGoal> is deprecated: use C66_Grasp-msg:C66_GraspActionGoal instead.")))

(cl:ensure-generic-function 'header-val :lambda-list '(m))
(cl:defmethod header-val ((m <C66_GraspActionGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader C66_Grasp-msg:header-val is deprecated.  Use C66_Grasp-msg:header instead.")
  (header m))

(cl:ensure-generic-function 'goal_id-val :lambda-list '(m))
(cl:defmethod goal_id-val ((m <C66_GraspActionGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader C66_Grasp-msg:goal_id-val is deprecated.  Use C66_Grasp-msg:goal_id instead.")
  (goal_id m))

(cl:ensure-generic-function 'goal-val :lambda-list '(m))
(cl:defmethod goal-val ((m <C66_GraspActionGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader C66_Grasp-msg:goal-val is deprecated.  Use C66_Grasp-msg:goal instead.")
  (goal m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <C66_GraspActionGoal>) ostream)
  "Serializes a message object of type '<C66_GraspActionGoal>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'header) ostream)
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'goal_id) ostream)
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'goal) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <C66_GraspActionGoal>) istream)
  "Deserializes a message object of type '<C66_GraspActionGoal>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'header) istream)
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'goal_id) istream)
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'goal) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<C66_GraspActionGoal>)))
  "Returns string type for a message object of type '<C66_GraspActionGoal>"
  "C66_Grasp/C66_GraspActionGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'C66_GraspActionGoal)))
  "Returns string type for a message object of type 'C66_GraspActionGoal"
  "C66_Grasp/C66_GraspActionGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<C66_GraspActionGoal>)))
  "Returns md5sum for a message object of type '<C66_GraspActionGoal>"
  "1b4d5bdaf2acb4ed8af192888fd82afa")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'C66_GraspActionGoal)))
  "Returns md5sum for a message object of type 'C66_GraspActionGoal"
  "1b4d5bdaf2acb4ed8af192888fd82afa")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<C66_GraspActionGoal>)))
  "Returns full string definition for message of type '<C66_GraspActionGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%Header header~%actionlib_msgs/GoalID goal_id~%C66_GraspGoal goal~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.secs: seconds (stamp_secs) since epoch~%# * stamp.nsecs: nanoseconds since stamp_secs~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%# 0: no frame~%# 1: global frame~%string frame_id~%~%================================================================================~%MSG: actionlib_msgs/GoalID~%# The stamp should store the time at which this goal was requested.~%# It is used by an action server when it tries to preempt all~%# goals that were requested before a certain time~%time stamp~%~%# The id provides a way to associate feedback and~%# result message with specific goal requests. The id~%# specified must be unique.~%string id~%~%~%================================================================================~%MSG: C66_Grasp/C66_GraspGoal~%# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal definition~%bool closed~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'C66_GraspActionGoal)))
  "Returns full string definition for message of type 'C66_GraspActionGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%Header header~%actionlib_msgs/GoalID goal_id~%C66_GraspGoal goal~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.secs: seconds (stamp_secs) since epoch~%# * stamp.nsecs: nanoseconds since stamp_secs~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%# 0: no frame~%# 1: global frame~%string frame_id~%~%================================================================================~%MSG: actionlib_msgs/GoalID~%# The stamp should store the time at which this goal was requested.~%# It is used by an action server when it tries to preempt all~%# goals that were requested before a certain time~%time stamp~%~%# The id provides a way to associate feedback and~%# result message with specific goal requests. The id~%# specified must be unique.~%string id~%~%~%================================================================================~%MSG: C66_Grasp/C66_GraspGoal~%# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal definition~%bool closed~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <C66_GraspActionGoal>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'header))
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'goal_id))
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'goal))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <C66_GraspActionGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'C66_GraspActionGoal
    (cl:cons ':header (header msg))
    (cl:cons ':goal_id (goal_id msg))
    (cl:cons ':goal (goal msg))
))
