/* Auto-generated by genmsg_cpp for file /home/darpa/Projects/Robil/C42_DynamicLocomotion/msg/C42_ZmpWlkAction.msg */
#ifndef C42_DYNAMICLOCOMOTION_MESSAGE_C42_ZMPWLKACTION_H
#define C42_DYNAMICLOCOMOTION_MESSAGE_C42_ZMPWLKACTION_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "C42_DynamicLocomotion/C42_ZmpWlkActionGoal.h"
#include "C42_DynamicLocomotion/C42_ZmpWlkActionResult.h"
#include "C42_DynamicLocomotion/C42_ZmpWlkActionFeedback.h"

namespace C42_DynamicLocomotion
{
template <class ContainerAllocator>
struct C42_ZmpWlkAction_ {
  typedef C42_ZmpWlkAction_<ContainerAllocator> Type;

  C42_ZmpWlkAction_()
  : action_goal()
  , action_result()
  , action_feedback()
  {
  }

  C42_ZmpWlkAction_(const ContainerAllocator& _alloc)
  : action_goal(_alloc)
  , action_result(_alloc)
  , action_feedback(_alloc)
  {
  }

  typedef  ::C42_DynamicLocomotion::C42_ZmpWlkActionGoal_<ContainerAllocator>  _action_goal_type;
   ::C42_DynamicLocomotion::C42_ZmpWlkActionGoal_<ContainerAllocator>  action_goal;

  typedef  ::C42_DynamicLocomotion::C42_ZmpWlkActionResult_<ContainerAllocator>  _action_result_type;
   ::C42_DynamicLocomotion::C42_ZmpWlkActionResult_<ContainerAllocator>  action_result;

  typedef  ::C42_DynamicLocomotion::C42_ZmpWlkActionFeedback_<ContainerAllocator>  _action_feedback_type;
   ::C42_DynamicLocomotion::C42_ZmpWlkActionFeedback_<ContainerAllocator>  action_feedback;


  typedef boost::shared_ptr< ::C42_DynamicLocomotion::C42_ZmpWlkAction_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::C42_DynamicLocomotion::C42_ZmpWlkAction_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct C42_ZmpWlkAction
typedef  ::C42_DynamicLocomotion::C42_ZmpWlkAction_<std::allocator<void> > C42_ZmpWlkAction;

typedef boost::shared_ptr< ::C42_DynamicLocomotion::C42_ZmpWlkAction> C42_ZmpWlkActionPtr;
typedef boost::shared_ptr< ::C42_DynamicLocomotion::C42_ZmpWlkAction const> C42_ZmpWlkActionConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::C42_DynamicLocomotion::C42_ZmpWlkAction_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::C42_DynamicLocomotion::C42_ZmpWlkAction_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace C42_DynamicLocomotion

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::C42_DynamicLocomotion::C42_ZmpWlkAction_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::C42_DynamicLocomotion::C42_ZmpWlkAction_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::C42_DynamicLocomotion::C42_ZmpWlkAction_<ContainerAllocator> > {
  static const char* value() 
  {
    return "292da403102e52c4fa09d324bb5a1dea";
  }

  static const char* value(const  ::C42_DynamicLocomotion::C42_ZmpWlkAction_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x292da403102e52c4ULL;
  static const uint64_t static_value2 = 0xfa09d324bb5a1deaULL;
};

template<class ContainerAllocator>
struct DataType< ::C42_DynamicLocomotion::C42_ZmpWlkAction_<ContainerAllocator> > {
  static const char* value() 
  {
    return "C42_DynamicLocomotion/C42_ZmpWlkAction";
  }

  static const char* value(const  ::C42_DynamicLocomotion::C42_ZmpWlkAction_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::C42_DynamicLocomotion::C42_ZmpWlkAction_<ContainerAllocator> > {
  static const char* value() 
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
\n\
C42_ZmpWlkActionGoal action_goal\n\
C42_ZmpWlkActionResult action_result\n\
C42_ZmpWlkActionFeedback action_feedback\n\
\n\
================================================================================\n\
MSG: C42_DynamicLocomotion/C42_ZmpWlkActionGoal\n\
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
\n\
Header header\n\
actionlib_msgs/GoalID goal_id\n\
C42_ZmpWlkGoal goal\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: actionlib_msgs/GoalID\n\
# The stamp should store the time at which this goal was requested.\n\
# It is used by an action server when it tries to preempt all\n\
# goals that were requested before a certain time\n\
time stamp\n\
\n\
# The id provides a way to associate feedback and\n\
# result message with specific goal requests. The id\n\
# specified must be unique.\n\
string id\n\
\n\
\n\
================================================================================\n\
MSG: C42_DynamicLocomotion/C42_ZmpWlkGoal\n\
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
#goal position and orientation\n\
geometry_msgs/Pose2D goal_pos\n\
float64 tol\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose2D\n\
# This expresses a position and orientation on a 2D manifold.\n\
\n\
float64 x\n\
float64 y\n\
float64 theta\n\
================================================================================\n\
MSG: C42_DynamicLocomotion/C42_ZmpWlkActionResult\n\
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
\n\
Header header\n\
actionlib_msgs/GoalStatus status\n\
C42_ZmpWlkResult result\n\
\n\
================================================================================\n\
MSG: actionlib_msgs/GoalStatus\n\
GoalID goal_id\n\
uint8 status\n\
uint8 PENDING         = 0   # The goal has yet to be processed by the action server\n\
uint8 ACTIVE          = 1   # The goal is currently being processed by the action server\n\
uint8 PREEMPTED       = 2   # The goal received a cancel request after it started executing\n\
                            #   and has since completed its execution (Terminal State)\n\
uint8 SUCCEEDED       = 3   # The goal was achieved successfully by the action server (Terminal State)\n\
uint8 ABORTED         = 4   # The goal was aborted during execution by the action server due\n\
                            #    to some failure (Terminal State)\n\
uint8 REJECTED        = 5   # The goal was rejected by the action server without being processed,\n\
                            #    because the goal was unattainable or invalid (Terminal State)\n\
uint8 PREEMPTING      = 6   # The goal received a cancel request after it started executing\n\
                            #    and has not yet completed execution\n\
uint8 RECALLING       = 7   # The goal received a cancel request before it started executing,\n\
                            #    but the action server has not yet confirmed that the goal is canceled\n\
uint8 RECALLED        = 8   # The goal received a cancel request before it started executing\n\
                            #    and was successfully cancelled (Terminal State)\n\
uint8 LOST            = 9   # An action client can determine that a goal is LOST. This should not be\n\
                            #    sent over the wire by an action server\n\
\n\
#Allow for the user to associate a string with GoalStatus for debugging\n\
string text\n\
\n\
\n\
================================================================================\n\
MSG: C42_DynamicLocomotion/C42_ZmpWlkResult\n\
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
#current position and orientation\n\
geometry_msgs/Pose2D res_pos\n\
float64 dis\n\
\n\
================================================================================\n\
MSG: C42_DynamicLocomotion/C42_ZmpWlkActionFeedback\n\
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
\n\
Header header\n\
actionlib_msgs/GoalStatus status\n\
C42_ZmpWlkFeedback feedback\n\
\n\
================================================================================\n\
MSG: C42_DynamicLocomotion/C42_ZmpWlkFeedback\n\
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
#feedback\n\
float64 dis_to_goal\n\
\n\
\n\
";
  }

  static const char* value(const  ::C42_DynamicLocomotion::C42_ZmpWlkAction_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::C42_DynamicLocomotion::C42_ZmpWlkAction_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.action_goal);
    stream.next(m.action_result);
    stream.next(m.action_feedback);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct C42_ZmpWlkAction_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::C42_DynamicLocomotion::C42_ZmpWlkAction_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::C42_DynamicLocomotion::C42_ZmpWlkAction_<ContainerAllocator> & v) 
  {
    s << indent << "action_goal: ";
s << std::endl;
    Printer< ::C42_DynamicLocomotion::C42_ZmpWlkActionGoal_<ContainerAllocator> >::stream(s, indent + "  ", v.action_goal);
    s << indent << "action_result: ";
s << std::endl;
    Printer< ::C42_DynamicLocomotion::C42_ZmpWlkActionResult_<ContainerAllocator> >::stream(s, indent + "  ", v.action_result);
    s << indent << "action_feedback: ";
s << std::endl;
    Printer< ::C42_DynamicLocomotion::C42_ZmpWlkActionFeedback_<ContainerAllocator> >::stream(s, indent + "  ", v.action_feedback);
  }
};


} // namespace message_operations
} // namespace ros

#endif // C42_DYNAMICLOCOMOTION_MESSAGE_C42_ZMPWLKACTION_H

