/* Auto-generated by genmsg_cpp for file /home/ariy/robil/C25_GlobalPosition/msg/C0C25_CAM.msg */
#ifndef C25_GLOBALPOSITION_MESSAGE_C0C25_CAM_H
#define C25_GLOBALPOSITION_MESSAGE_C0C25_CAM_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace C25_GlobalPosition
{
template <class ContainerAllocator>
struct C0C25_CAM_ {
  typedef C0C25_CAM_<ContainerAllocator> Type;

  C0C25_CAM_()
  : frameRatePerSec(0)
  {
  }

  C0C25_CAM_(const ContainerAllocator& _alloc)
  : frameRatePerSec(0)
  {
  }

  typedef int32_t _frameRatePerSec_type;
  int32_t frameRatePerSec;


  typedef boost::shared_ptr< ::C25_GlobalPosition::C0C25_CAM_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::C25_GlobalPosition::C0C25_CAM_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct C0C25_CAM
typedef  ::C25_GlobalPosition::C0C25_CAM_<std::allocator<void> > C0C25_CAM;

typedef boost::shared_ptr< ::C25_GlobalPosition::C0C25_CAM> C0C25_CAMPtr;
typedef boost::shared_ptr< ::C25_GlobalPosition::C0C25_CAM const> C0C25_CAMConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::C25_GlobalPosition::C0C25_CAM_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::C25_GlobalPosition::C0C25_CAM_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace C25_GlobalPosition

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::C25_GlobalPosition::C0C25_CAM_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::C25_GlobalPosition::C0C25_CAM_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::C25_GlobalPosition::C0C25_CAM_<ContainerAllocator> > {
  static const char* value() 
  {
    return "0556698a1696c5e5a613abb4fe2bb569";
  }

  static const char* value(const  ::C25_GlobalPosition::C0C25_CAM_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x0556698a1696c5e5ULL;
  static const uint64_t static_value2 = 0xa613abb4fe2bb569ULL;
};

template<class ContainerAllocator>
struct DataType< ::C25_GlobalPosition::C0C25_CAM_<ContainerAllocator> > {
  static const char* value() 
  {
    return "C25_GlobalPosition/C0C25_CAM";
  }

  static const char* value(const  ::C25_GlobalPosition::C0C25_CAM_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::C25_GlobalPosition::C0C25_CAM_<ContainerAllocator> > {
  static const char* value() 
  {
    return "int32 frameRatePerSec\n\
\n\
";
  }

  static const char* value(const  ::C25_GlobalPosition::C0C25_CAM_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::C25_GlobalPosition::C0C25_CAM_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::C25_GlobalPosition::C0C25_CAM_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.frameRatePerSec);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct C0C25_CAM_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::C25_GlobalPosition::C0C25_CAM_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::C25_GlobalPosition::C0C25_CAM_<ContainerAllocator> & v) 
  {
    s << indent << "frameRatePerSec: ";
    Printer<int32_t>::stream(s, indent + "  ", v.frameRatePerSec);
  }
};


} // namespace message_operations
} // namespace ros

#endif // C25_GLOBALPOSITION_MESSAGE_C0C25_CAM_H

