C42_LocomotionAndStability/C34C42_WM Work_mode_msg
C42_LocomotionAndStability/C34C42_PSU Desired_Path_state_update_msg
---
C42_LocomotionAndStability/C42C34_CS Current_work_mode_msg
C42_LocomotionAndStability/C42C34_EVE Events_msg
