(cl:defpackage C65_CloseValve-msg
  (:use )
  (:export
   "<C65_CLOSEVALVERESULT>"
   "C65_CLOSEVALVERESULT"
   "<C65_CLOSEVALVEGOAL>"
   "C65_CLOSEVALVEGOAL"
   "<C65_CLOSEVALVEACTIONFEEDBACK>"
   "C65_CLOSEVALVEACTIONFEEDBACK"
   "<C65_CLOSEVALVEFEEDBACK>"
   "C65_CLOSEVALVEFEEDBACK"
   "<C65_CLOSEVALVEACTIONGOAL>"
   "C65_CLOSEVALVEACTIONGOAL"
   "<C65_CLOSEVALVEACTION>"
   "C65_CLOSEVALVEACTION"
   "<C65_CLOSEVALVEACTIONRESULT>"
   "C65_CLOSEVALVEACTIONRESULT"
  ))

