/* Auto-generated by genmsg_cpp for file /home/ariy/robil/C65_CloseValve/msg/C65_CloseValveAction.msg */
#ifndef C65_CLOSEVALVE_MESSAGE_C65_CLOSEVALVEACTION_H
#define C65_CLOSEVALVE_MESSAGE_C65_CLOSEVALVEACTION_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "C65_CloseValve/C65_CloseValveActionGoal.h"
#include "C65_CloseValve/C65_CloseValveActionResult.h"
#include "C65_CloseValve/C65_CloseValveActionFeedback.h"

namespace C65_CloseValve
{
template <class ContainerAllocator>
struct C65_CloseValveAction_ {
  typedef C65_CloseValveAction_<ContainerAllocator> Type;

  C65_CloseValveAction_()
  : action_goal()
  , action_result()
  , action_feedback()
  {
  }

  C65_CloseValveAction_(const ContainerAllocator& _alloc)
  : action_goal(_alloc)
  , action_result(_alloc)
  , action_feedback(_alloc)
  {
  }

  typedef  ::C65_CloseValve::C65_CloseValveActionGoal_<ContainerAllocator>  _action_goal_type;
   ::C65_CloseValve::C65_CloseValveActionGoal_<ContainerAllocator>  action_goal;

  typedef  ::C65_CloseValve::C65_CloseValveActionResult_<ContainerAllocator>  _action_result_type;
   ::C65_CloseValve::C65_CloseValveActionResult_<ContainerAllocator>  action_result;

  typedef  ::C65_CloseValve::C65_CloseValveActionFeedback_<ContainerAllocator>  _action_feedback_type;
   ::C65_CloseValve::C65_CloseValveActionFeedback_<ContainerAllocator>  action_feedback;


  typedef boost::shared_ptr< ::C65_CloseValve::C65_CloseValveAction_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::C65_CloseValve::C65_CloseValveAction_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct C65_CloseValveAction
typedef  ::C65_CloseValve::C65_CloseValveAction_<std::allocator<void> > C65_CloseValveAction;

typedef boost::shared_ptr< ::C65_CloseValve::C65_CloseValveAction> C65_CloseValveActionPtr;
typedef boost::shared_ptr< ::C65_CloseValve::C65_CloseValveAction const> C65_CloseValveActionConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::C65_CloseValve::C65_CloseValveAction_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::C65_CloseValve::C65_CloseValveAction_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace C65_CloseValve

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::C65_CloseValve::C65_CloseValveAction_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::C65_CloseValve::C65_CloseValveAction_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::C65_CloseValve::C65_CloseValveAction_<ContainerAllocator> > {
  static const char* value() 
  {
    return "c29f3d2056fcd9404762cae3b12aba05";
  }

  static const char* value(const  ::C65_CloseValve::C65_CloseValveAction_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xc29f3d2056fcd940ULL;
  static const uint64_t static_value2 = 0x4762cae3b12aba05ULL;
};

template<class ContainerAllocator>
struct DataType< ::C65_CloseValve::C65_CloseValveAction_<ContainerAllocator> > {
  static const char* value() 
  {
    return "C65_CloseValve/C65_CloseValveAction";
  }

  static const char* value(const  ::C65_CloseValve::C65_CloseValveAction_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::C65_CloseValve::C65_CloseValveAction_<ContainerAllocator> > {
  static const char* value() 
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
\n\
C65_CloseValveActionGoal action_goal\n\
C65_CloseValveActionResult action_result\n\
C65_CloseValveActionFeedback action_feedback\n\
\n\
================================================================================\n\
MSG: C65_CloseValve/C65_CloseValveActionGoal\n\
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
\n\
Header header\n\
actionlib_msgs/GoalID goal_id\n\
C65_CloseValveGoal goal\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: actionlib_msgs/GoalID\n\
# The stamp should store the time at which this goal was requested.\n\
# It is used by an action server when it tries to preempt all\n\
# goals that were requested before a certain time\n\
time stamp\n\
\n\
# The id provides a way to associate feedback and\n\
# result message with specific goal requests. The id\n\
# specified must be unique.\n\
string id\n\
\n\
\n\
================================================================================\n\
MSG: C65_CloseValve/C65_CloseValveGoal\n\
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
#goal definition\n\
float32[2] location\n\
int32 max\n\
\n\
================================================================================\n\
MSG: C65_CloseValve/C65_CloseValveActionResult\n\
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
\n\
Header header\n\
actionlib_msgs/GoalStatus status\n\
C65_CloseValveResult result\n\
\n\
================================================================================\n\
MSG: actionlib_msgs/GoalStatus\n\
GoalID goal_id\n\
uint8 status\n\
uint8 PENDING         = 0   # The goal has yet to be processed by the action server\n\
uint8 ACTIVE          = 1   # The goal is currently being processed by the action server\n\
uint8 PREEMPTED       = 2   # The goal received a cancel request after it started executing\n\
                            #   and has since completed its execution (Terminal State)\n\
uint8 SUCCEEDED       = 3   # The goal was achieved successfully by the action server (Terminal State)\n\
uint8 ABORTED         = 4   # The goal was aborted during execution by the action server due\n\
                            #    to some failure (Terminal State)\n\
uint8 REJECTED        = 5   # The goal was rejected by the action server without being processed,\n\
                            #    because the goal was unattainable or invalid (Terminal State)\n\
uint8 PREEMPTING      = 6   # The goal received a cancel request after it started executing\n\
                            #    and has not yet completed execution\n\
uint8 RECALLING       = 7   # The goal received a cancel request before it started executing,\n\
                            #    but the action server has not yet confirmed that the goal is canceled\n\
uint8 RECALLED        = 8   # The goal received a cancel request before it started executing\n\
                            #    and was successfully cancelled (Terminal State)\n\
uint8 LOST            = 9   # An action client can determine that a goal is LOST. This should not be\n\
                            #    sent over the wire by an action server\n\
\n\
#Allow for the user to associate a string with GoalStatus for debugging\n\
string text\n\
\n\
\n\
================================================================================\n\
MSG: C65_CloseValve/C65_CloseValveResult\n\
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
#result definition\n\
bool success\n\
\n\
================================================================================\n\
MSG: C65_CloseValve/C65_CloseValveActionFeedback\n\
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
\n\
Header header\n\
actionlib_msgs/GoalStatus status\n\
C65_CloseValveFeedback feedback\n\
\n\
================================================================================\n\
MSG: C65_CloseValve/C65_CloseValveFeedback\n\
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
#feedback\n\
float32[2] location\n\
\n\
\n\
";
  }

  static const char* value(const  ::C65_CloseValve::C65_CloseValveAction_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::C65_CloseValve::C65_CloseValveAction_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.action_goal);
    stream.next(m.action_result);
    stream.next(m.action_feedback);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct C65_CloseValveAction_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::C65_CloseValve::C65_CloseValveAction_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::C65_CloseValve::C65_CloseValveAction_<ContainerAllocator> & v) 
  {
    s << indent << "action_goal: ";
s << std::endl;
    Printer< ::C65_CloseValve::C65_CloseValveActionGoal_<ContainerAllocator> >::stream(s, indent + "  ", v.action_goal);
    s << indent << "action_result: ";
s << std::endl;
    Printer< ::C65_CloseValve::C65_CloseValveActionResult_<ContainerAllocator> >::stream(s, indent + "  ", v.action_result);
    s << indent << "action_feedback: ";
s << std::endl;
    Printer< ::C65_CloseValve::C65_CloseValveActionFeedback_<ContainerAllocator> >::stream(s, indent + "  ", v.action_feedback);
  }
};


} // namespace message_operations
} // namespace ros

#endif // C65_CLOSEVALVE_MESSAGE_C65_CLOSEVALVEACTION_H

