/* Auto-generated by genmsg_cpp for file /home/ariy/robil/C42_LocomotionAndStability/msg/C42C34_CS.msg */
#ifndef C42_LOCOMOTIONANDSTABILITY_MESSAGE_C42C34_CS_H
#define C42_LOCOMOTIONANDSTABILITY_MESSAGE_C42C34_CS_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace C42_LocomotionAndStability
{
template <class ContainerAllocator>
struct C42C34_CS_ {
  typedef C42C34_CS_<ContainerAllocator> Type;

  C42C34_CS_()
  : Current_Work_mode(0)
  {
  }

  C42C34_CS_(const ContainerAllocator& _alloc)
  : Current_Work_mode(0)
  {
  }

  typedef int32_t _Current_Work_mode_type;
  int32_t Current_Work_mode;


  typedef boost::shared_ptr< ::C42_LocomotionAndStability::C42C34_CS_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::C42_LocomotionAndStability::C42C34_CS_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct C42C34_CS
typedef  ::C42_LocomotionAndStability::C42C34_CS_<std::allocator<void> > C42C34_CS;

typedef boost::shared_ptr< ::C42_LocomotionAndStability::C42C34_CS> C42C34_CSPtr;
typedef boost::shared_ptr< ::C42_LocomotionAndStability::C42C34_CS const> C42C34_CSConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::C42_LocomotionAndStability::C42C34_CS_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::C42_LocomotionAndStability::C42C34_CS_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace C42_LocomotionAndStability

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::C42_LocomotionAndStability::C42C34_CS_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::C42_LocomotionAndStability::C42C34_CS_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::C42_LocomotionAndStability::C42C34_CS_<ContainerAllocator> > {
  static const char* value() 
  {
    return "ec759d9d3247a59c422ebbc9f9301793";
  }

  static const char* value(const  ::C42_LocomotionAndStability::C42C34_CS_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xec759d9d3247a59cULL;
  static const uint64_t static_value2 = 0x422ebbc9f9301793ULL;
};

template<class ContainerAllocator>
struct DataType< ::C42_LocomotionAndStability::C42C34_CS_<ContainerAllocator> > {
  static const char* value() 
  {
    return "C42_LocomotionAndStability/C42C34_CS";
  }

  static const char* value(const  ::C42_LocomotionAndStability::C42C34_CS_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::C42_LocomotionAndStability::C42C34_CS_<ContainerAllocator> > {
  static const char* value() 
  {
    return "int32 Current_Work_mode\n\
\n\
";
  }

  static const char* value(const  ::C42_LocomotionAndStability::C42C34_CS_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::C42_LocomotionAndStability::C42C34_CS_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::C42_LocomotionAndStability::C42C34_CS_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.Current_Work_mode);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct C42C34_CS_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::C42_LocomotionAndStability::C42C34_CS_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::C42_LocomotionAndStability::C42C34_CS_<ContainerAllocator> & v) 
  {
    s << indent << "Current_Work_mode: ";
    Printer<int32_t>::stream(s, indent + "  ", v.Current_Work_mode);
  }
};


} // namespace message_operations
} // namespace ros

#endif // C42_LOCOMOTIONANDSTABILITY_MESSAGE_C42C34_CS_H

