"""autogenerated by genpy from C23_ObjectRecognition/C23C0_ODIM.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import C23_ObjectRecognition.msg

class C23C0_ODIM(genpy.Message):
  _md5sum = "bb2056bb72057f005681e4ca255f0766"
  _type = "C23_ObjectRecognition/C23C0_ODIM"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """C23_ObjectRecognition/TBD min_dimensions
C23_ObjectRecognition/TBD max_dimensions

================================================================================
MSG: C23_ObjectRecognition/TBD
int32 x
int32 y
int32 z

"""
  __slots__ = ['min_dimensions','max_dimensions']
  _slot_types = ['C23_ObjectRecognition/TBD','C23_ObjectRecognition/TBD']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       min_dimensions,max_dimensions

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(C23C0_ODIM, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.min_dimensions is None:
        self.min_dimensions = C23_ObjectRecognition.msg.TBD()
      if self.max_dimensions is None:
        self.max_dimensions = C23_ObjectRecognition.msg.TBD()
    else:
      self.min_dimensions = C23_ObjectRecognition.msg.TBD()
      self.max_dimensions = C23_ObjectRecognition.msg.TBD()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_6i.pack(_x.min_dimensions.x, _x.min_dimensions.y, _x.min_dimensions.z, _x.max_dimensions.x, _x.max_dimensions.y, _x.max_dimensions.z))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.min_dimensions is None:
        self.min_dimensions = C23_ObjectRecognition.msg.TBD()
      if self.max_dimensions is None:
        self.max_dimensions = C23_ObjectRecognition.msg.TBD()
      end = 0
      _x = self
      start = end
      end += 24
      (_x.min_dimensions.x, _x.min_dimensions.y, _x.min_dimensions.z, _x.max_dimensions.x, _x.max_dimensions.y, _x.max_dimensions.z,) = _struct_6i.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_6i.pack(_x.min_dimensions.x, _x.min_dimensions.y, _x.min_dimensions.z, _x.max_dimensions.x, _x.max_dimensions.y, _x.max_dimensions.z))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.min_dimensions is None:
        self.min_dimensions = C23_ObjectRecognition.msg.TBD()
      if self.max_dimensions is None:
        self.max_dimensions = C23_ObjectRecognition.msg.TBD()
      end = 0
      _x = self
      start = end
      end += 24
      (_x.min_dimensions.x, _x.min_dimensions.y, _x.min_dimensions.z, _x.max_dimensions.x, _x.max_dimensions.y, _x.max_dimensions.z,) = _struct_6i.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_6i = struct.Struct("<6i")
