/* Auto-generated by genmsg_cpp for file /home/sharon/ROS_ROBIL_ROOT/robil/C46_MountVehicle/msg/MountFeedback.msg */
#ifndef C46_MOUNTVEHICLE_MESSAGE_MOUNTFEEDBACK_H
#define C46_MOUNTVEHICLE_MESSAGE_MOUNTFEEDBACK_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace C46_MountVehicle
{
template <class ContainerAllocator>
struct MountFeedback_ {
  typedef MountFeedback_<ContainerAllocator> Type;

  MountFeedback_()
  : percent_complete(0.0)
  {
  }

  MountFeedback_(const ContainerAllocator& _alloc)
  : percent_complete(0.0)
  {
  }

  typedef float _percent_complete_type;
  float percent_complete;


  typedef boost::shared_ptr< ::C46_MountVehicle::MountFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::C46_MountVehicle::MountFeedback_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct MountFeedback
typedef  ::C46_MountVehicle::MountFeedback_<std::allocator<void> > MountFeedback;

typedef boost::shared_ptr< ::C46_MountVehicle::MountFeedback> MountFeedbackPtr;
typedef boost::shared_ptr< ::C46_MountVehicle::MountFeedback const> MountFeedbackConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::C46_MountVehicle::MountFeedback_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::C46_MountVehicle::MountFeedback_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace C46_MountVehicle

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::C46_MountVehicle::MountFeedback_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::C46_MountVehicle::MountFeedback_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::C46_MountVehicle::MountFeedback_<ContainerAllocator> > {
  static const char* value() 
  {
    return "d342375c60a5a58d3bc32664070a1368";
  }

  static const char* value(const  ::C46_MountVehicle::MountFeedback_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xd342375c60a5a58dULL;
  static const uint64_t static_value2 = 0x3bc32664070a1368ULL;
};

template<class ContainerAllocator>
struct DataType< ::C46_MountVehicle::MountFeedback_<ContainerAllocator> > {
  static const char* value() 
  {
    return "C46_MountVehicle/MountFeedback";
  }

  static const char* value(const  ::C46_MountVehicle::MountFeedback_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::C46_MountVehicle::MountFeedback_<ContainerAllocator> > {
  static const char* value() 
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
# Define a feedback message\n\
float32 percent_complete\n\
\n\
\n\
";
  }

  static const char* value(const  ::C46_MountVehicle::MountFeedback_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::C46_MountVehicle::MountFeedback_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::C46_MountVehicle::MountFeedback_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.percent_complete);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct MountFeedback_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::C46_MountVehicle::MountFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::C46_MountVehicle::MountFeedback_<ContainerAllocator> & v) 
  {
    s << indent << "percent_complete: ";
    Printer<float>::stream(s, indent + "  ", v.percent_complete);
  }
};


} // namespace message_operations
} // namespace ros

#endif // C46_MOUNTVEHICLE_MESSAGE_MOUNTFEEDBACK_H

