(cl:defpackage C0_RobilTask-msg
  (:use )
  (:export
   "<ROBILTASKRESULT>"
   "ROBILTASKRESULT"
   "<ROBILTASKGOAL>"
   "ROBILTASKGOAL"
   "<ROBILTASKFEEDBACK>"
   "ROBILTASKFEEDBACK"
   "<ROBILTASKACTION>"
   "ROBILTASKACTION"
   "<ROBILTASKACTIONGOAL>"
   "ROBILTASKACTIONGOAL"
   "<ROBILTASKACTIONFEEDBACK>"
   "ROBILTASKACTIONFEEDBACK"
   "<ROBILTASKACTIONRESULT>"
   "ROBILTASKACTIONRESULT"
  ))

