(cl:defpackage C46_MountVehicle-msg
  (:use )
  (:export
   "<MOUNTFEEDBACK>"
   "MOUNTFEEDBACK"
   "<MOUNTRESULT>"
   "MOUNTRESULT"
   "<MOUNTACTIONRESULT>"
   "MOUNTACTIONRESULT"
   "<MOUNTACTIONFEEDBACK>"
   "MOUNTACTIONFEEDBACK"
   "<MOUNTACTION>"
   "MOUNTACTION"
   "<MOUNTACTIONGOAL>"
   "MOUNTACTIONGOAL"
   "<MOUNTGOAL>"
   "MOUNTGOAL"
  ))

