; Auto-generated. Do not edit!


(cl:in-package C46_MountVehicle-msg)


;//! \htmlinclude MountResult.msg.html

(cl:defclass <MountResult> (roslisp-msg-protocol:ros-message)
  ((mounted
    :reader mounted
    :initarg :mounted
    :type cl:float
    :initform 0.0))
)

(cl:defclass MountResult (<MountResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <MountResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'MountResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name C46_MountVehicle-msg:<MountResult> is deprecated: use C46_MountVehicle-msg:MountResult instead.")))

(cl:ensure-generic-function 'mounted-val :lambda-list '(m))
(cl:defmethod mounted-val ((m <MountResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader C46_MountVehicle-msg:mounted-val is deprecated.  Use C46_MountVehicle-msg:mounted instead.")
  (mounted m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <MountResult>) ostream)
  "Serializes a message object of type '<MountResult>"
  (cl:let ((bits (roslisp-utils:encode-single-float-bits (cl:slot-value msg 'mounted))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <MountResult>) istream)
  "Deserializes a message object of type '<MountResult>"
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'mounted) (roslisp-utils:decode-single-float-bits bits)))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<MountResult>)))
  "Returns string type for a message object of type '<MountResult>"
  "C46_MountVehicle/MountResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'MountResult)))
  "Returns string type for a message object of type 'MountResult"
  "C46_MountVehicle/MountResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<MountResult>)))
  "Returns md5sum for a message object of type '<MountResult>"
  "8e265b97fe86999f6bcce88ace33a325")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'MountResult)))
  "Returns md5sum for a message object of type 'MountResult"
  "8e265b97fe86999f6bcce88ace33a325")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<MountResult>)))
  "Returns full string definition for message of type '<MountResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the result~%float32 mounted~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'MountResult)))
  "Returns full string definition for message of type 'MountResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the result~%float32 mounted~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <MountResult>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <MountResult>))
  "Converts a ROS message object to a list"
  (cl:list 'MountResult
    (cl:cons ':mounted (mounted msg))
))
