(cl:in-package C43_LocalBodyPVA-srv)
(cl:export '(SELECTED_JOINT_MSG-VAL
          SELECTED_JOINT_MSG
          SELECTED_LINK_MSG-VAL
          SELECTED_LINK_MSG
          SELECTED_INFORMATION_MSG-VAL
          SELECTED_INFORMATION_MSG
          SELECTED_LINK_INFORMATION_MSG-VAL
          SELECTED_LINK_INFORMATION_MSG
          PVA_OF_REQUESTED_JOINT_MSG-VAL
          PVA_OF_REQUESTED_JOINT_MSG
          PVA_OF_REQUESTED_LINK_LOCAL_REF_FRAME_MSG-VAL
          PVA_OF_REQUESTED_LINK_LOCAL_REF_FRAME_MSG
))