(cl:in-package C24_ObstacleDetection-srv)
(cl:export '(AZIMUTH-VAL
          AZIMUTH
          CAMERA_SAMPLE_RATE-VAL
          CAMERA_SAMPLE_RATE
          LASER_SAMPLE_RATE-VAL
          LASER_SAMPLE_RATE
          MINIMUM_OBSTACLE_SIZE-VAL
          MINIMUM_OBSTACLE_SIZE
          OBJECTDETECTED-VAL
          OBJECTDETECTED
          OBJECTPOSSITION-VAL
          OBJECTPOSSITION
          OBJECTDIMENSIONS-VAL
          OBJECTDIMENSIONS
))