C48_StandUp/C0C48_JSI Joints_values_msg
C48_StandUp/C0C48_TRN Terrain_Type_msg
C48_StandUp/C0C48_SLP Slope_msg
C48_StandUp/C0C48_COM COM_msg
---
C48_StandUp/C48C0_Status StandUp_Status_msg
C48_StandUp/C48C0_Err StandUp_Error_msg
